version: '3.8'

services:
    app:
        build: .
        ports:
            - "9000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
